services:

  nginx:

    build:

      context: ./nginx

      dockerfile: Dockerfile

    container_name: nginx-container

    ports:

      - "80:80"

    depends_on:

      - frontend

      - backend

  frontend:

    build:

      context: ./frontend

      dockerfile: Dockerfile

    container_name: frontend-container

  backend:

    build:

      context: ./backend

      dockerfile: Dockerfile

    container_name: backend-container
