services:



  frontend:

    build:

      context: ./frontend

      dockerfile: Dockerfile

    container_name: frontend-container

    ports:

      - "8080:80"



  backend-1:

    build:

      context: ./backend

      dockerfile: Dockerfile

    container_name: backend-container-1

    ports:

      - "3000:3000"



  backend-2:

    build:

      context: ./backend

      dockerfile: Dockerfile

    container_name: backend-container-2

    ports:

      - "3001:3000"



  nginx:

    build:

      context: ./nginx

      dockerfile: Dockerfile

    container_name: nginx-container

    ports:

      - "80:80"

    depends_on:

      - frontend

      - backend-1

      - backend-2
