services:

  nginx:

    image: nginx:alpine

    container_name: nginx-container

    ports:

      - "80:80"

    volumes:

      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    # volumes:

    # - type: bind

    #   source: ./nginx/nginx.conf

    #   target: /etc/nginx/nginx.conf

    depends_on:

      - frontend

      - backend



  frontend:

    build:

      context: ./frontend

      dockerfile: Dockerfile

    container_name: frontend-container

    # no ports: needed — nginx handles routing



  backend:

    build:

      context: ./backend

      dockerfile: Dockerfile

    container_name: backend-container

    # no ports: needed — nginx handles routing

